package testing_lib.accessModifierClazzConstructorAccessIncreasePrivateToProtected;

public class AccessModifierClazzConstructorAccessIncreasePrivateToProtected {

    protected AccessModifierClazzConstructorAccessIncreasePrivateToProtected() {}

}