package testing_lib.accessModifierClazzConstructorAccessIncreaseProtectedToPublic;

public class AccessModifierClazzConstructorAccessIncreaseProtectedToPublic {

    public AccessModifierClazzConstructorAccessIncreaseProtectedToPublic() {}

}