package accessModifierClazzNestedIfazeAccessDecrease;

import testing_lib.accessModifierClazzNestedIfazeAccessDecrease.AccessModifierClazzNestedIfazeAccessDecrease.IfazePublicToNon;
import testing_lib.accessModifierClazzNestedIfazeAccessDecrease.AccessModifierClazzNestedIfazeAccessDecrease.IfazePublicToPrivate;
import testing_lib.accessModifierClazzNestedIfazeAccessDecrease.AccessModifierClazzNestedIfazeAccessDecrease.IfazePublicToProtected;

public class Main implements IfazePublicToProtected, IfazePublicToNon, IfazePublicToPrivate {

	
	
}
